name: pixiv
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # State
  provider: ^4.3.2+2
  webview_flutter: ^0.3.22+1
  flutter_webview_plugin: ^0.3.11
  pull_to_refresh: ^1.6.2
  flutter_swiper: ^1.1.6
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  shared_preferences: 0.5.10
  # 本地json对象存储
  localstorage: ^3.0.2+5
  # 根据arb生成dart文件
  # flutter pub pub run intl_translation:generate_from_arb --output-dir=lib/generated --no-use-deferred-loading lib/generated/l10n.dart lib/l10n/intl_*.arb
  intl_translation: ^0.17.10+1
  device_info: ^1.0.0
  package_info: ^0.4.3
  # Html Encoder/Decoder
  html_unescape: ^1.0.2
  # 解析html标签
  flutter_html: ^1.0.2
  bot_toast: ^3.0.5
  sqflite: ^1.3.1+2
  permission_handler: ^5.0.1+1
  lottie: ^0.7.0+1
  cached_network_image: ^2.3.3
  like_button: ^0.1.9
  flutter_svg: ^0.18.0
  flutter_tags: ^0.4.9+1
  flutter_widget_from_html_core: ^0.5.1+3
  url_launcher: ^5.7.8
  share: ^0.6.5+3
  keyboard_visibility: 0.5.6
  flutter_linkify: ^4.0.2
  photo_view: ^0.10.3
  extended_image: ^1.5.0
  image_gallery_saver: ^1.6.7
  path_provider: ^1.6.24
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: MPLUS1p
      fonts:
        - asset: assets/fonts/MPLUS1p-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-SemiBold.ttf

  assets:
    - assets/lottie/
    - assets/images/

flutter_intl:
  enabled: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
